### ISSUE TITLE
macOS 10.12

### ISSUE THREAD

**Issue by clarkml** [sheagcraig/yo#14]
Seeing an issue with macOS 10.12 GM1 and GM2 at this point.  We cannot get the action or bash action to work at all.  10.11 or 10.10 of course works fine.  Not sure what has changed, sure it's on Apple's side.  Any news on when 10.12 will be supported via Yo official?  We love making use of it.

**Comment by clarkml** [comment]
Well it appears this is only an issue with our compiled version to customize the app icon.  The package here works fine.  What could that be?

**Comment by sheagcraig** [comment]
Hey @clarkml.

I just pushed a Swift 3 / Xcode 8 version to the testing branch if you want to try that.

Both the "action" and "bash action" seem to be working in my testing. Let me know how it goes for you!

**Comment by clarkml** [comment]
Hey awesome!  We’ll check it out and provide feedback. I do believe we refactored to Swift 2.3 and that allowed us to get by.  I’m thankful for this app, makes a huge different on the experience of alerting our users.

Thank you!
