### ISSUE TITLE
Casper Extension Attributes

### ISSUE THREAD

**Issue by grahampugh** [sheagcraig/yo#18]
I couldn't follow the instructions for creating a Casper extension attribute. The instructions state "add the EA to your JSS", but what does this mean?  I cannot upload `yo-casper-extension-attribute.py` to the JSS (only XML files are valid), and running `./yo-casper-extension-attribute.py` does nothing except output `<result>True</result>` to Stdin.

**Comment by tulgeywood** [comment]
You don't upload it to the JSS but rather create a new EA in Jamf and the paste the text of the python script. The python script will then be executed each time the computer does a recon.

**Comment by grahampugh** [comment]
Apologies - Casper newbie, hadn't seen the Scripts option of EA.....
Thanks for the tip.
