### ISSUE TITLE
-z not working

### ISSUE THREAD

**Issue by erikng** [sheagcraig/yo#2]
-z /System/Library/Sounds/Glass

Specifying any sounds still only results in a generic noise being generated.

**Comment by sheagcraig** [comment]
That one is a little tricky. It expects JUST the filename without the extension or path.

So if you want Glass, put `-z Glass`. As long as the sound is in one of the search paths listed in the README it should work.

**Comment by erikng** [comment]
Ah! I misread the readme.

**Comment by erikng** [comment]
Could you add /System/Library/PrivateFrameworks/ToneLibrary.framework/Versions/A/Resources/AlertTones and the sub folders to the default search paths?

**Comment by sheagcraig** [comment]
At first I thought that wouldn't be possible. The NSUserNotification.soundName option takes a named system sound. See [here](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSSound_Class/index.html#//apple_ref/occ/clm/NSSound/soundNamed:). So I don't set the search path-that's cooked into AppKit.

But I think I can add another option that will allow you to pass a complete path. If it's present, then I can create a sound object with that filename and assign it a name. Next release!

**Comment by erikng** [comment]
Sweet! Can't wait. :)

**Comment by sheagcraig** [comment]
@erikng Hey man-so I tried taking an arbitrary path, creating an NSSound instance, naming it, and then using that named sound, and it didn't work.

But, that being said, the initWithFileNamed method searches through the sound search paths for a file with the right name and will use that successfully. It's now documented in the new version, but for example, you could deploy a sound for yo usage like this:

```
# Directory probably doesn't exist yet.
mkdir /Library/Sounds
cp ~/Desktop/TheHumptyDance.aiff /Library/Sounds/
# Uses the new built-in (to the package installer) shell script...
yo -t "Limp to the side like your legs are broken..." -z "TheHumptyDance"
```

Note that the sound HAS to be an aiff, with an extension of `.aiff`, not `.aif`. And you don't specify the path at all, or the extension.
