### ISSUE TITLE
Cannot open Applications (--action-path)

### ISSUE THREAD

**Issue by danshaw** [sheagcraig/yo#21]
I've implemented yo using Casper and everything is working except I cannot get applications to launch. I've tried some 3rd party apps and even tried the native calculator app and nothing is opening. Any ideas why this might be happening?

Testing using MacOS 10.12.3.

<img width="338" alt="screenshot 2017-02-24 14 47 07" src="https://cloud.githubusercontent.com/assets/6180024/23322227/31563984-faa0-11e6-9fab-e47d56da4934.png">

**Comment by mikevmeyer** [comment]
@sheagcraig can probably help clarify, but I'm pretty sure you have to actually write out the command.

For example, you can't just have "/Applications/Calculator.app", as the action.

You have to say: "open /Applications/Calculator.app"

The action path allows you to run unix commands.
I use it in casper in the "Files and Processes" payload, and just invoke yo by calling in the "Execute Command" field. Try adding "open" to your Action Path box pictured, and see if that does the trick.

**Comment by erikng** [comment]
x2 what Mike said. I'm apple to open applications with Yo without issue in 10.12.3

Thanks,
Erik Gomez

________________________________

**Comment by danshaw** [comment]
Well strange. It's not working for me still. Here is what is output, but the open button doesn't do anything. Tried it with quotes and without.

`2017-03-10 14:26:15,'/Applications/Utilities/yo.app/Contents/MacOS/yo --title Calculator --info Open it up --action-btn Open --action-path open /Applications/Calculator.app',2d407d251807a16aaf10484387b7475e`

**Comment by mikevmeyer** [comment]
This is how I use it (you can copy/paste this code into terminal):

`open /Applications/Utilities/yo.app --args -t 'Calculator' -n 'Open it up' -b 'Open' -a '/Applications/Calculator.app'`

Should work like a charm.

I also used shorthand codes for your flags (i.e., "-t" in place of "--title".).

One other thing to note (and I'm just realizing this, after I suggested that earlier fix) is that if you're using this in casper, make it a one line code in the Files and processes payload, in the execute command field.  After the full command, I always add:
`; logger 'Posting Notification'`

So a full casper execution code would look like this:
`open /Applications/Utilities/yo.app --args -t 'Calculator' -n 'Open it up' -b 'Open' -a '/Applications/Calculator.app'; logger 'Posting Notification'`

There's a specific reason why this needs to be done, and I know sheacraig mentions it somewhere in the readme... excuse me for not remembering. :)
