### ISSUE TITLE
Yo with LaunchDaemon

### ISSUE THREAD

**Issue by horizontalz** [sheagcraig/yo#23]
I've been trying to have Yo notify the user every 10 seconds to log into Google Drive with a LaunchDaemon that runs at load but it doesn't seem to work.  

If I run the  .sh script manually, it works.  

Might there some issue with LaunchDaemons and notifications?

**Comment by tulgeywood** [comment]
Try a launchagent. Daemons load at login screen when you aren't supposed to make GUI calls.

**Comment by horizontalz** [comment]
Yes, I had to fire it up with a LaunchAgent so I had to set one up in conjunction with the LaunchDaemon.
