### ISSUE TITLE
Swift compiler error while building form source

### ISSUE THREAD

**Issue by pleegor** [sheagcraig/yo#29]
Hi all, 

I am trying to build package from its source and I am running into "/Users/pleegor/Documents/yo-master/yo/CommandLine.swift:315:76: Result values in '? :' expression have mismatching types 'Substring.SubSequence' (aka 'Substring') and '_'" any idea how this can be fixed?

**Comment by sheagcraig** [comment]
I haven't built in awhile, let me do a new one with some of the pending changes and see what's up.

**Comment by sheagcraig** [comment]
I just built it for Swift 4.
