### ISSUE TITLE
Triggering Action Inadvertantly 

### ISSUE THREAD

**Issue by mpermann** [sheagcraig/yo#30]
In testing a notification with an action tied to an Action button, I've noticed the action can be triggered by clicking anywhere within the notification excluding the Other button location. I would expect the action would only be triggered if you click the Action button itself. I've noticed this behavior in macOS 10.13 and 10.12. Is this normal behavior?

**Comment by sheagcraig** [comment]
Yes, there's basically nothing we can do to change the way notifications actually work, I'm afraid.
