### ISSUE TITLE
yo_scheduler not getting added in the default PATH

### ISSUE THREAD

**Issue by ghostSystem** [sheagcraig/yo#34]
The Build was successful. But the yo_scheduler was never copied to /usr/local/bin/yo_scheduler path. After copying yo.app to Applications and running `yo_scheduler -t "This is amazing"` nothing happens. It says invalid command (obvious because there is no path).

Also there is no Launch Agent for the yo_scheduler process.

I followed the exact steps that were mentioned.
Downloaded the project -> Build in Xcode version 9.3 (build succeeded) -> went into products and copied the yo.app to /Applications.

What is wrong here ?

**Comment by sheagcraig** [comment]
The pkg subfolder includes the materials to build a deployable package installer, which includes the yo scheduler.

See https://github.com/sheagcraig/yo#package-build-and-deployment
