### ISSUE TITLE
Build fails on Xcode 10.2

### ISSUE THREAD

**Issue by wegotoeleven** [sheagcraig/yo#38]
Hey. Yo won't compile on Xcode 10.2, as 10.2 doesn't support Swift 3. Do you have plans to update to Swift 4/5?

**Comment by sheagcraig** [comment]
Yep. Will do as soon as Xcode 10.1 downloads so I can do it!

**Comment by wegotoeleven** [comment]
So about 4 days?! 🤣 

Thanks!

**Comment by sheagcraig** [comment]
That's how long the xip archive takes to decompress... I'm really tempted to see if I can upgrade to Swift 4 in less time than it takes for that.

**Comment by sheagcraig** [comment]
Okay @wegotoeleven. Check #39

**Comment by sheagcraig** [comment]
I'll update to Swift 5 here in a little. I'm researching how to replace command line argument processing.

**Comment by sheagcraig** [comment]
Swift 5 update complete. Go ahead and test away and let me know how it's working for you.

**Comment by wegotoeleven** [comment]
So far, this looks good, with testing on 10.14.4. I'm yet to test this on any version prior to 10.14.4, and I'm aware that Xcode 10.2 doesn't compile certain libraries into the project, as mentioned here (https://scriptingosx.com/2019/04/swift-5-for-macadmins/), so I'll report back when I've done some tests. Thanks for doing this!

**Comment by sheagcraig** [comment]
It superficially sounds like we'll be fine for now; Yo is an application bundle, so the libs will be compiled in. However, I'm looking at how to move forward after the retirement of the CommandLine parser project, and one option is to rewrite yo just as a command line app. So this is very helpful information.

**Comment by arubdesu** [comment]
Consider this report `#2` of this swift5 code working on Xcode 10.2/10.14.4 in limited testing so far, thanks G!

**Comment by wegotoeleven** [comment]
I'd say this issue is closed! :)
