### ISSUE TITLE
Execute bash scripts from -a argument

### ISSUE THREAD

**Issue by sheagcraig** [sheagcraig/yo#5]
@tulgeywood requests the ability to run bash scripts from the -a command.

**Comment by tulgeywood** [comment]
Thanks for the quick follow up on this. Love the tool already but this would really kick up the usefulness.

**Comment by sheagcraig** [comment]
@tulgeywood 
It's in! Check the new version's documentation.

`-B` or `--bash-action` will allow you to provide a quoted bash command to execute.
