### ISSUE TITLE
--action-path not working after Big Sur 11.6 update

### ISSUE THREAD

**Issue by mallej** [sheagcraig/yo#55]
Looks like clicking on the notifications  --action-path does not open the apps anymore when on macOS 11.6

**Comment by mallej** [comment]
In Monterey Beta 6 it is still working as aspected.

**Comment by msiege2** [comment]
I see this too on 11.6.  action-path seems to do nothing.

**Comment by str8outtajc** [comment]
I can confirm this broke with 11.6

**Comment by niloque** [comment]
Tested yo.app today on a developer beta version of Big Sur 11.6.1 and seems to be working. Hopefully that will be the case for the production release of that version.

**Comment by tristanthomas** [comment]
Confirmed this feature is working on Big Sur 11.6.1 RC (20G219) and Monterey 12.0 Beta 10 (21A5552a)

**Comment by memile123** [comment]
Its not working after the 11.6 update on our machines also.

**Comment by dan-snelson** [comment]
Yo version `2.0.2` is working as expected for us (to open a URL) on macOS 11.6.1 (20G224) and macOS 12.0.1 (21A559).

**Comment by mallej** [comment]
I am closing this issue as it only affects 11.6.0.
