### ISSUE TITLE
Autopkg recipe for yo?

### ISSUE THREAD

**Issue by everetteallen** [sheagcraig/yo#7]
Was looking for an autopkg recipe for yo.pkg but not finding one.  Did I miss it?

**Comment by sheagcraig** [comment]
Hey @everetteallen:
I have one for it... I use it for building the release packages here. Apparently I never posted it.

**Comment by sheagcraig** [comment]
Actually, I take that back. I build the release packages with a The Luggage makefile. I'll craft one up for stock yo here soon.

**Comment by sheagcraig** [comment]
Done!
